services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: charge_flow_backend
    command: sleep infinity
    network_mode: host
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/postgresql:/var/run/postgresql
