events {}

http {
    server {
        listen 80;
        server_name app.opower.su;
        # front
        location / {
            proxy_pass http://frontend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    # bacckend
    server {
        listen 80;
        server_name api.opower.su;
        
        location / {
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    # dev
    server {
        listen 80;
        server_name dev.opower.su;
        location / {
            proxy_pass http://frontend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}