events {}

http {

    # === PROD FRONT ===
    server {
        listen 80;
        server_name app.opower.su;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # === API ===
    server {
        listen 80;
        server_name api.opower.su;

        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # === DEV ===
    server {
        listen 80;
        server_name dev.opower.su;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}