events {}

http {
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }

    server {
        listen 443 ssl default_server;
        server_name _;
        ssl_certificate /etc/letsencrypt/live/dev.opower.su/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dev.opower.su/privkey.pem;
        return 444;
    }
    # http -> https
    server {
        listen 80;
        server_name dev.opower.su app.opower.su api.opower.su;
        return 301 https://$host$request_uri;
    } 
   


    # DEV (Должен быть закрыт)
    server {
        listen 443 ssl;
        server_name dev.opower.su;

        ssl_certificate /etc/letsencrypt/live/dev.opower.su/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dev.opower.su/privkey.pem;

        auth_basic "Dev Access";
        auth_basic_user_file /opt/nginx-auth/.htpasswd;

        location / {
            proxy_pass http://frontend:8080;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://api:8000/;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    # Prod
    server {
        listen 443 ssl;
        server_name app.opower.su;
        return 503;
        
        ssl_certificate /etc/letsencrypt/live/dev.opower.su/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dev.opower.su/privkey.pem;

        location / {
            proxy_pass http://127.0.0.1:8081;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/ {
            proxy_pass http://127.0.0.1:8001/;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # API
    server {
        listen 443 ssl;
        server_name api.opower.su;

        ssl_certificate /etc/letsencrypt/live/dev.opower.su/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dev.opower.su/privkey.pem;

        location / {
            proxy_pass http://api:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}