name: Deploy Project Dev

on:
  push:
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy frontend over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/chargeflow_dev
            git fetch --all
            git reset --hard origin/main
            docker compose up -d --build frontend
            docker image prune -f